sudo: false
language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4
env:
  - PKG_DIR=names-th
  - PKG_DIR=sql-words
  - PKG_DIR=persistable-record
  - PKG_DIR=relational-query
  - PKG_DIR=relational-schemas
  - PKG_DIR=HDBC-session
  - PKG_DIR=relational-query-HDBC
  - PKG_DIR=relational-record
  - PKG_DIR=text-postgresql
  - PKG_DIR=persistable-types-HDBC-pg
before_install:
  - date
  - echo $PATH
  - which cabal ; cabal --version ; dpkg -l cabal-install
  - find /usr/local/ghc/*/bin -type f -ls
  - which ghc   ; ghc --version   ; dpkg -l ghc ;
  - cd $PKG_DIR
after_script:
  - date
