language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4
before_install:
  - date
  - cd relational-query
script:
  - cabal configure --enable-tests && cabal build --verbose=2 && pwd && cabal test --verbose=2
after_script:
  - date
