language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4
before_install:
  - date
  - cd relational-query
script:
  - cabal configure --enable-tests && cabal build && find dist/build -ls && cabal test || find dist/build -ls
after_script:
  - date
