packages:
  - HDBC-session/
  - names-th/
  - persistable-record/
  - relational-query/
  - relational-query-HDBC/
#  - relational-query-HDBC/example/mysql/
#  - relational-query-HDBC/example/Oracle/
#  - relational-query-HDBC-pgTest/
  - relational-record/
#  - relational-record-examples/
  - relational-schemas/
  - sql-words/
extra-deps:
  - HDBC-2.4.0.1
#  - HDBC-mysql-0.6.6.1
#  - HDBC-odbc-2.4.0.1
#  - HDBC-postgresql-2.3.2.3
#  - HDBC-sqlite3-2.3.3.1
resolver: lts-3.0
